// src/js/Applications/Components/DeckCapture/SettingModal.vue
<template>
  <div class="modal" :class="{active}" id="modal-id">
    <a href="#close" class="modal-overlay" aria-label="Close"></a>
    <div class="modal-container">
      <div class="modal-header">
        <a href="#close" class="btn btn-clear float-right" aria-label="Close"></a>
        <div class="modal-title h5">Modal title</div>
      </div>
      <div class="modal-body">
        <div class="content">
          <!-- content here -->
        </div>
      </div>
      <div class="modal-footer">
        ...
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import {Vue, Component, Prop} from "vue-property-decorator";

@Component
export default class SettingModal extends Vue {
  @Prop() private active: boolean;
}
</script>

// src/js/Applications/Components/DeckCapture/SettingModal.tsx
import React, { Component } from "react";
import cn from "classnames";

export default class SettingModal extends Component<{active: boolean}> {
  render() {
    const {active} = this.props;
    return (
      <div className={cn("modal", {active})} id="modal-id">
        <a href="#close" className="modal-overlay" aria-label="Close"></a>
        <div className="modal-container">
          <div className="modal-header">
            <a href="#close" className="btn btn-clear float-right" aria-label="Close"></a>
            <div className="modal-title h5">Modal title</div>
          </div>
          <div className="modal-body">
            <div className="content">
            </div>
          </div>
          <div className="modal-footer">
            ...
          </div>
        </div>
      </div>
    );
  }
}
