// src/js/Applications/Components/DeckCapture/SideBar.tsx
import React, { Component } from "react";
import DeckCapture from "../../Models/DeckCapture";


export default class SideBar extends Component<{
  onSelect: (DeckCapture) => any;
  settings: DeckCapture[];
  selected: string;
  preview: string;
  row, col, page: number;
}> {
  render() {
    const {settings, selected, preview, row, col, page} = this.props;
    return (
      <div className="container sidebar">
        <div className="form-group">
          <select className="form-select" onChange={this.props.onSelect}>
            {settings.map(s => <option value={s._id} selected={selected == s._id}>{s.title}</option>)}
          </select>
        </div>

        <div className="preview-container">
          <div id="preview">
            <img src={preview} style={{width: "100%", display: "block"}} />
          </div>
        </div>

        <div className="input-group">
          <input type="number" className="form-input" value={row} />
          <span className="input-group-addon">行</span>
        </div>

        <div className="input-group">
          <input type="number" className="form-input" value={col} />
          <span className="input-group-addon">列</span>
        </div>

        <div className="input-group">
          <input type="number" className="form-input" value={page} />
          <span className="input-group-addon">ページ</span>
        </div>

      </div>
    );
  }
}

// src/js/Applications/Components/DeckCapture/SideBar.vue
<template>
  <div class="container sidebar">

    <div class="form-group">
      <select class="form-select" @change="onSelect">
        <option
          v-for="s in settings"
          :key="s.title"
          :value="s._id"
          :selected="selected == s._id"
        >{{s.title}}</option>
      </select>
    </div>

    <div class="preview-container">
      <div id="preview">
        <img v-bind:src="preview" style="width: 100%; display: block;"/>
      </div>
    </div>

    <div class="input-group">
      <input type="number" class="form-input" :value="row">
      <span class="input-group-addon">行</span>
    </div>

    <div class="input-group">
      <input type="number" class="form-input" :value="col">
      <span class="input-group-addon">列</span>
    </div>

    <div class="input-group">
      <input type="number" class="form-input" :value="page">
      <span class="input-group-addon">ページ</span>
    </div>

  </div>
</template>
<script lang="ts">
import {Vue, Component, Prop} from "vue-property-decorator";
import DeckCapture from "../../Models/DeckCapture";

@Component
export default class SideBar extends Vue {
  @Prop() private settings: DeckCapture[];
  @Prop() private selected: string;
  @Prop() private onSelect: (DeckCapture) => any;

  @Prop() private preview: string;

  @Prop() private row: number;
  @Prop() private col: number;
  @Prop() private page  : number;
}

</script>
