// src/js/Applications/Components/Options/DamageSnapshot/index.vue
<template>
  <section class="category">
    <h1>大破進撃防止機能</h1>
    <config v-bind:config="damagesnapshot" />
    <config v-if="damagesnapshot.value == 'inapp'" :config="inappdsnapshotsize" />
    <config v-if="damagesnapshot.value != 'disabled'" v-bind:config="inappdsnapshotctx" />
  </section>
</template>
<script lang="ts">
import {Vue,Component} from "vue-property-decorator";

import Config, {Category} from "../../../Models/Config";
import ConfigView from "../Config/index.vue";
import DamageSnapshotFrame from "../../../Models/DamageSnapshotFrame";

@Component({
  components: {"config": ConfigView},
})
export default class InApp extends Vue {

  private damagesnapshot: DamageSnapshotFrame;
  private inappdsnapshotsize: Config<number>;
  private inappdsnapshotctx: Config<boolean>;

  constructor() {
    super();
    this.damagesnapshot = DamageSnapshotFrame.get();
    this.inappdsnapshotsize = Config.find("inapp-dsnapshot-size");
    this.inappdsnapshotctx = Config.find("inapp-dsnapshot-context");
  }
}
</script>

// src/js/Applications/Components/Options/DamageSnapshot/index.tsx
import React, { Component } from "react";

import DamageSnapshotFrame, {DamageSnapshotType} from "../../../Models/DamageSnapshotFrame";
import Config from "../../../Models/Config";
import ConfigView from "../Config";

// TODO: これもうちょいいい方法無いの
//       デコレータ的なやつで
declare interface State {
  damagesnapshot: DamageSnapshotFrame;
  inappdsnapshotsize: Config<number>;
  inappdsnapshotctx: Config<boolean>;
}

export default class DamageSnapshotOptions extends Component<{}, State> {

  constructor(props) {
    super(props);
    this.state = {
      damagesnapshot: DamageSnapshotFrame.get(),
      inappdsnapshotsize: Config.find("inapp-dsnapshot-size"),
      inappdsnapshotctx: Config.find("inapp-dsnapshot-context"),
    }
  }
  render() {
    return (
      <section className="category">
        <h1>大破進撃防止機能</h1>
        <ConfigView config={this.state.damagesnapshot as Config<any>} />
        {this.state.damagesnapshot.value == DamageSnapshotType.InApp ? <ConfigView config={this.state.inappdsnapshotsize} /> : null}
        {this.state.damagesnapshot.value != DamageSnapshotType.Disabled ? <ConfigView config={this.state.inappdsnapshotctx} /> : null}
      </section>
    );
  }
}
