// src/js/Applications/Components/Options/Debugger/index.tsx
import React, { Component } from "react";

import Simulator from "./Simulator";

export default class DebuggerView extends Component {
    render() {
        return (
            <div className="category">
                <h1>Dev Debugger</h1>
                <Simulator />
            </div>
        );
    }
}

// src/js/Applications/Components/Options/Debugger/index.vue
<template>
  <div class="category">
    <h1>Dev Debugger</h1>
    <simulator />
  </div>
</template>
<script lang="ts">
import {Vue, Component} from "vue-property-decorator";
import Simulator from "./Simulator.vue";

@Component({
  components: {
    "simulator": Simulator,
  },
})
export default class Debugger extends Vue {}
</script>
