// src/js/Applications/Components/Popup/index.tsx
import React, {Component} from "react";

import LaunchTrigger from "./LaunchTrigger";
import IconMenu from "./IconMenu";

export default class PopupPage extends Component {
    render() {
        return (
            <div className="container popup" style={{width: "320px"}}>
                <LaunchTrigger />
                <IconMenu />
            </div>
        );
    }
}

// src/js/Applications/Components/Popup.vue
<template>
  <div class="container popup" style="width: 320px;">
    <launch-trigger />
  </div>
</template>
<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import LaunchTrigger from "./Popup/LaunchTrigger.vue";

@Component({
  components: {
    "launch-trigger": LaunchTrigger,
  }
})
export default class Popup extends Vue {
  foobar() {
    alert("hogeeeee");
  }
}

</script>
