// src/js/Applications/Components/Options/Config/CategorySection.tsx
import React, { Component } from "react";
import Config from "../../../Models/Config";
import ConfigView from "./index";

// とくに相互依存が無くて表示ロジックが凝っていない設定カテゴリはこのコンポーネントを使ってください
export default class CategorySection extends Component<{title:string, configs:Config<any>[]}> {
  render() {
    const {title, configs} = this.props;
    return (
      <section className="category">
        <h1>{title}</h1>
        {configs.map(config => <ConfigView key={config._id} config={config} />)}
      </section>
    );
  }
}

// src/js/Applications/Components/Options/Config/CategorySection.vue
<!-- とくに相互依存が無くて表示ロジックが凝っていない設定カテゴリはこのコンポーネントを使ってください -->
<template>
  <section class="category">
    <h1>{{title}}</h1>
    <config v-for="c in configs" :key="c.title" :config="c" />
  </section>  
</template>
<script lang="ts">
import {Vue,Component,Prop} from "vue-property-decorator";
import Config from "../../../Models/Config";
import ConfigView from "./index.vue";
@Component({components: {"config": ConfigView}})
export default class CategorySection extends Vue {
  @Prop() private title: string;
  @Prop() private configs: Config<any>[];
}
</script>
