// src/js/Applications/Components/Options/Config/index.tsx
import React, { Component } from "react";
import Config, {Type as ConfigType} from "../../../Models/Config";

import SwitchConfig from "./switch-config";
import SelectConfig from "./select-config";
import NumberConfig from "./number-config";

export default class ConfigView extends Component<{ config: Config<any> }, {}> {
    render() {
        return (
            <div className="columns">
                {this._renderContent()}
            </div>
        );
    }
    _renderContent() {
        switch (this.props.config.type) {
            case ConfigType.Switch:
                return <SwitchConfig config={this.props.config} />;
            case ConfigType.Select:
                return <SelectConfig config={this.props.config} />;
            case ConfigType.Number:
                return <NumberConfig config={this.props.config} />;
            default:
                return null;
        }
    }
}

// src/js/Applications/Components/Options/Config/index.vue
<template>
  <div class="columns">
    <switch-config v-if="config.type == 'switch'" v-bind:config="config" />
    <select-config v-else-if="config.type == 'select'" v-bind:config="config" />
    <number-config v-else-if="config.type == 'number'" :config="config" />
  </div>
</template>
<script lang="ts">
import {Vue, Component, Prop} from "vue-property-decorator";

import SwitchConfig from "./switch-config.vue";
import SelectConfig from "./select-config.vue";
import NumberConfig from "./number-config.vue";

import Config from "../../../Models/Config";

@Component({
  components: {
    "switch-config": SwitchConfig,
    "select-config": SelectConfig,
    "number-config": NumberConfig,
  }
})
export default class ConfigView extends Vue {
  @Prop({type: Config}) private config: Config<any>;
}
</script>
