// src/js/Applications/Components/Options/Config/number-config.tsx
import React, { Component } from "react";

import Config from "../../../Models/Config";

export default class NumberConfig extends Component<{config: Config<number>}> {
    render() {
        return (
            <div className="column col-10">
                <div className="tile">
                    <div className="tile-content">
                        <h5 className="tile-title">{this.props.config.title}</h5>
                        <p className="tile-subtitle text-gray">{this.props.config.description}</p>
                    </div>
                    <div className="tile-action">
                        <div className="form-group">
                            <input
                                onChange={(ev) => this.onChange(ev)}
                                className="form-input"
                                type="number"
                                value={this.props.config.value}
                                step={this.props.config.step}
                                min={this.props.config.range[0]}
                                max={this.props.config.range[1]}
                            />
                        </div>
                    </div>
                </div>
            </div>
        );
    }
    private onChange(ev: {target: HTMLInputElement}) {
        this.props.config.update({value: parseInt(ev.target.value)});
    }
}

// src/js/Applications/Components/Options/Config/number-config.vue
<template>
  <div class="column col-10">
    <div class="tile">
      <div class="tile-content">
        <h5 class="tile-title">{{config.title}}</h5>
        <p class="tile-subtitle text-gray">{{config.description}}</p>
      </div>
      <div class="tile-action">
        <div class="form-group">
          <input
            @change="onchange"
            class="form-input"
            type="number"
            :value="config.value"
            :step="config.step"
            :min="config.range[0]"
            :max="config.range[1]"
          />
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import {Vue, Component, Prop} from "vue-property-decorator";
import Config from "../../../Models/Config";

@Component
export default class NumberConfig extends Vue {
  @Prop({type: Config}) private config: Config<number>;
  onchange(ev: {target: HTMLInputElement}) {
    this.config.update({value: parseInt(ev.target.value)});
  }
}
</script>
