// src/js/Applications/Components/Options/Config/select-config.vue
<template>
  <div class="column col-10">
    <div class="tile">
      <div class="tile-content">
        <h5 class="tile-title">{{config.title}}</h5>
        <p class="tile-subtitle text-gray">{{config.description}}</p>
      </div>
      <div class="tile-action">
        <div class="form-group">
          <select class="form-select" @change="onchange">
            <option
              v-for="opt in config.options"
              :value="opt.value"
              :key="opt.value"
              :selected="opt.value == config.value"
            >{{opt.name}}</option>
          </select>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import {Vue, Component, Prop} from "vue-property-decorator";
import Config from "../../../Models/Config";

@Component
export default class SelectConfig extends Vue {

  @Prop({type: Config})
  private config: Config<string>;

  onchange(ev: {target: HTMLInputElement}) {
    this.config.update({value: ev.target.value});
  }

}
</script>

// src/js/Applications/Components/Options/Config/select-config.tsx
import React, { Component } from "react";
import Config from "../../../Models/Config";

// TODO: this.props.configがだるいので、...Configで渡したい
export default class SelectConfig extends Component<{config: Config<any>}> {
  render() {
    return (
      <div className="column col-10">
        <div className="tile">
          <div className="tile-content">
            <h5 className="tile-title">{this.props.config.title}</h5>
            <p className="tile-subtitle text-gray">{this.props.config.description}</p>
          </div>
          <div className="tile-action">
            <div className="form-group">
              <select className="form-select" onChange={ev => this.onChange(ev)}>
                {this.props.config.options.map(opt => {
                  return (
                    <option
                      value={opt.value}
                      key={opt.value}
                      selected={opt.value == this.props.config.value}
                    >{opt.name}</option>
                  );
                })}
              </select>
            </div>
          </div>
        </div>
      </div>
    );
  }
  private onChange(ev) {
    this.props.config.update({value: ev.target.value});
  }
}
