// src/js/Applications/Components/Options/Config/switch-config.tsx
import React, { Component } from "react";

import Config from "../../../Models/Config";

export default class SwitchConfig extends Component<{config:Config<any>}> {
  render() {
    return (
      <div className="column col-10">
        <div className="tile">
          <div className="tile-content">
            <h5 className="tile-title">{this.props.config.title}</h5>
            <p className="tile-subtitle text-gray">{this.props.config.description}</p>
          </div>
          <div className="tile-action">
            <div className="form-group">
              <label className="form-switch">
                <input type="checkbox" v-model="config.value" onChange={ev => this.onChange(ev)} />
                <i className="form-icon" />
              </label>
            </div>
          </div>
        </div>
      </div>
    );
  }
  
  private onChange(ev) {
    this.props.config.update({value: ev.target.checked});
  }
}

// src/js/Applications/Components/Options/Config/switch-config.vue
<template>
  <div class="column col-10">
    <div class="tile">
      <div class="tile-content">
        <p class="tile-title">{{config.title}}</p>
        <p class="tile-subtitle text-gray">{{config.description}}</p>
      </div>
      <div class="tile-action">
        <div class="form-group">
          <label class="form-switch">
            <input type="checkbox" v-model="config.value" @change="onchange">
            <i class="form-icon"></i>
          </label>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import {Vue, Component, Prop} from "vue-property-decorator";

import Config from "../../../Models/Config";

@Component
export default class SwitchConfig extends Vue {

  @Prop({type: Config})
  private config: Config<boolean>;

  onchange(ev: {target: HTMLInputElement}) {
    this.config.update({value: ev.target.checked});
  }

}
</script>
